encoding/encoding_test.go, framework/import_test.go, framework/reflect.go
This fixes an issue where a null value in a map would get deleted because `SetMapIndex` with the zero reflect value as the value would _delete_ the map entry. 
To resolve this, for invalid values we set the value to the zero value of the _type_ (not the zero value of the `reflect.Value`) which sets the proper value.
=> framework: nil entries in map should be preserved

framework/import.go, framework/import_test.go
There's currently an off-by-one error on the error reporting with keys.
Example: A get or call error on import.foo.bar("baz") would only report
"foo", and import.foo("bar") would just return a blank string ("").
This corrects that. It also shifts the tests over to allow the
validation of the error message as well, and adds a little bit more
coverage.
=> framework: Report keys properly on Get error messages

framework/import.go, framework/import_test.go
A consequence of the multi-key function call work that has been
added in #23 is that any key past a function call will now be called
after the function call.
Example: json.unmarshal("{\"foo\": null}").foo, which would normally
return the map {"foo": null}, now will fully traverse the map,
returning the underlying null.
Tests that we have for the json import in the core runtime have
revealed an issue in the way we deeply traverse raw maps (not
namespaces) in that if the final value is nil, we treat it as
undefined (like it was the result of a Get call), even though our map
value conversion will convert nils found in map return values to zero
values (so nil for a map[string]interface{}).
This commit fixes that logic so that things function as expected
again.
=> framework: ensure null return on deep map get with nil value

framework/import_test.go, plugin.go, rpc/import_grpc_server.go, rpc/import_grpc_test.go
This moves the Keys field to type []GetKey instead of []*GetKey.
This is possibly a matter of personal preference but after some
discussion internally there are some marginal benefits, namely with
nil not being meaningful in this context.
=> sdk: move GetKey field in GetReq to a value slice

.circleci/config.yml, go.mod
This is for Circle and the directive in go.mod.
=> Go: use Go 1.13

framework/import.go, framework/import_test.go
The changes in #25 fixed a problem where (explicit) nulls were
incorrectly being returned as undefined, rather than null. The changes,
however, effectively cut this behavior fully over to null, including the
cases were unknown keys were retrieved.
This fixes it so that unknown keys continue to correctly return
undefined.
=> framework: ensure Get for an unknown key on a map returns undefined

Makefile
Due to the protocol flux that was a part of the recent update to the SDK
and runtime, it was not possible to test the acceptance testing
framework in the "testing" package until Sentinel v0.11.0 was released.
Now that this has been done, we can start testing this stuff again.
=> Makefile: use Sentinel v0.11.0 and re-active tests for "testing"

.circleci/config.yml, Makefile
This fixes the Sentinel test binary caching for Circle.
The current setup was actually completely ineffective as using a
"restore_cache" clause with two keys only restores one key at a time.
This means if there was a go module cache, Sentinel would be skipped.
Additionally, we've observed in other repositories that the Sentinel
cache restore was failing altogether with permission issues. As such,
this also moves the Sentinel binary to a place where it can be restored
with non-root permissions (we use the "go install" binary path here).
=> Circle: fix Sentinel test binary caching for CI

encoding/encoding_test.go, encoding/go_to_value.go, framework/framework.go, framework/import.go
This fixes a couple of things having to do with how we marshal structs
into Sentinel RPC objects:
* The previous logic in toValue_struct for creating the list of elements
was basically running under the assumption that *all* struct fields were
exported and were not being skipped, by using a make call with a full
length based on the struct's NumField. This means that there's a
possibility of nils making it to the protobuf marshaling where they fail
because a protobuf message can't be nil. The fix is to use NumField for
capacity and set the initial length of the slice to 0, using append to
populate instead.
* The behavior for field name conversion was also not matching with the
documentation - we were not converting field names to lowercase. This
has now been fixed - the default name for …
=> encoding: struct field marshaling fixes

testing/import.go, testing/import_test.go
I realized that it was difficult to write tests for policy functionality we expect to fail, and most tests are happy-path / successful. I could be missing something, but if there's not another way to do this, this seemed like an ok way of allowing testing runtime errors emitted by plugins.
=> testing: allow testing for runtime errors

rpc/import_grpc_client.go, rpc/serve.go
Pass options to the gRPC server so that it will accept large messages. Currently the default gRPC server only allows 4MB. We want to allow plugins to return larger data structures.
This change copies [what Vault does](https://github.com/hashicorp/vault/blob/master/sdk/plugin/serve.go#L73-L74). Terraform also modifies this default. This gives us some assurance that bumping this value up shouldn't cause stability concerns.
=> rpc: increase the maximum grpc message size

framework/import_test.go
This just adds a test to illustrate that a bare framework.Namespace that
does not include framework.Map will be passed through the lower-level
framework.Get method okay, which should make it available for conversion
and subject to the same rules as any other struct.
=> framework: add test to illustrate non-Map interface passthrough

testing/import.go, testing/import_test.go
Currently all tests require writing the import name as `subject`. This doesn't reflect a realistic name for the import and makes tests a bit more obtuse to write.
With this change we'd allow the test implementation to pass a more realistic name for the import on a test-by-test basis, which could then be used within the policy source.
=> testing: allow specifying the import name

testing/import.go, testing/import_test.go, testing/testdata/import-test-dir/nope.txt, testing/testdata/import-test-dir/subdir/bad.sentinel, testing/testdata/import-test-dir/test.sentinel, testing/testdata/test.sentinel
Adds helper functions to load `TestImportCase` structures from Sentinel policy files using simple pragmas. The idea is to get out of the habit of infinitely adding to our table tests, especially when we start having more complex and multi-line policies. The process of adding a test simply becomes dropping a new policy file into a directory.
=> Add helpers for loading TestImportCase structures

testing/import.go, testing/import_test.go, testing/testdata/import-test-dir/error-pragma-regex.sentinel
This allows an Error string to contain a regular expression to be compiled and matched against the error output. If the Error string is delimited by slashes, it's used as a regular expression. Otherwise, the normal behavior (substring to be contained in the error output) is preserved.
Examples:
```go
// Direct helper API
TestImportCase{Error: `normal substring`}
TestImportCase{Error: "normal substring"}
TestImportCase{Error: `/a \w+ pattern/`}
TestImportCase{Error: "/a \\w+ pattern/"}
```
```
//error normal substring
//error /a \w+ pattern/
```
Errors in the given error pattern are helpfully surfaced, though this I found to be basically impossible to test because I don't know how to get the output to match on. (It's still tested, but like a similar other test in the suite, it just ensures …
=> Add regular expression support to TestImportCase.Error

framework/import.go, framework/import_test.go
Change the way we present errors from function calls on a namespace to not include the full key path. The key path doesn't seem to add any value to the error messages and instead makes them a little more awkward to parse.
A couple of examples to help understand:
```
import "http"
main = rule { http.with_timeout(30).get(url) }
```
Before:
```
error calling function "with_timeout.get": expected status code to be one of [200], got 500
```
After:
```
error calling function "get": expected status code to be one of [200], got 500
```
```
import "time"
main = rule { time.load(123).before("nope") }
```
Before (also lol at the randomness of this error):
```
error calling function "load.before": parsing time "nope" as "2006-01-02T15:04:05.999999999Z07:00": cannot parse "nope" as "2006"
```
After: …
=> framework: shorten key path in errors during method chaining

encoding/encoding_test.go, framework/import_test.go, framework/reflect.go
This fixes an issue with the post-Get value handler and slices/lists
with null elements, handling them in a fashion similar to how maps
handle these values (added in 9f5e918e).
=> framework: handle nils in slices

framework/import_test.go, framework/reflect.go
Concurrency scenarios that involve deep reflection of import namespaces
with deep maps and slices can create problems during reflection of a Get
result that ultimately create two problems:
* Concurrent modification of a map, or concurrent iteration *and*
modification of a map. We do not perform any locking on this data, and,
given that the result should be read-only at this point, there should
not need to be.
* The above alludes to the fact that the current result reflection is
actually modifying the result value in-place when it comes to maps and
slices. This method is assuming that the data in the result is actually
a copy of any underlying import data, which is actually not the case -
in addition to the nuances of Go map and slice internals, the return
data could contain direct …
=> framework: ensure result reflection is thread safe and immutable

framework/import_test.go, framework/reflect.go
Issue #45 incorrectly assumed all maps coming from return data would be
string-keyed. This is not the case.
This fixes things to allow for non-string-keyed values to be returned.
We still use a hard interface{} as the value type.
=> framework: ensure new map copy logic works for non-string keys

testing/import.go
Previous the testing framework would build the import without a .exe
extension on Windows. This meant that sentinel could not craft a
configuration which would make it execute the import file. In turn
this meant that the SDK could not be used to test imports on Windows
systems which is one of the use cases for this SDK
This commit updates the import builder to add the .exe extension
on Windows systems.
=> Use .exe extension on built imports

.github/workflows/get-go-version.yml
This commit removes the deprecated set-output command and instead uses the supported environment file [1]
[1] https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> Remove deprecated set-output

framework/interface.go, framework/plugin.go, framework/plugin_test.go, framework/reflect.go
To help enable further capabilities within the SDK, this PR adds a `List` interface to allow namespaces to return a list of data.
=> Add list interface

.github/dependabot.yml, .github/workflows/get-go-version.yml, .github/workflows/test.yml
This commit updates the GH actions to use NodeJS20. This also adds a dependabot file to update these regularly
=> Update GH Actions to NodeJS 20

rpc/plugin.go, rpc/plugin_grpc_client.go, rpc/plugin_grpc_server.go, rpc/plugin_grpc_test.go, rpc/plugin_test.go, rpc/serve.go
CHANGELOG: Changed the import order for all the Go files in the sentinel-sdk repository.
Fixed the import order of the libraries used by all the Go files following the logic below:
- standard library
- 3rd party dependencies (not including hashicorp dependencies)
- hashicorp dependencies
- local dependencies
This change does not require any testing plan.
- [JIRA task](https://hashicorp.atlassian.net/browse/TF-6589)
=> TF-6589: Ensure import order is consistent throughout Sentinel repositories

.gitignore, plugin.go, plugin_test.go
Currently the `sdk.Null` type marshals as `{}` when using the `encoding/json` package. This PR will fix that so that it marshals to `null` as expected.
=> Add MarshalJSON for sdk.Null, ensuring conversion the same as Go nil
